version: '3'

services:
  postgres: &postgres
    image: postgres:12.1
    container_name: godmin_db_dev
    restart: always
    environment:
      - POSTGRES_DB=godmin_db_dev
      - POSTGRES_USER=godmin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/postgres/init/:/docker-entrypoint-init.d/
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  postgres_test:
    container_name: godmin_db_test
    environment:
      - POSTGRES_DB=godmin_db_test
      - POSTGRES_USER=godmin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/postgres/init/:/docker-entrypoint-init.d/
    ports:
      - 7432:5432
    <<: *postgres
