name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run services
      run: docker-compose -f docker-compose.yml up -d postgres_test redis_test

    - name: Test
      run: make test

    - name: Build image
      run: make image
