name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run docker-compose
      run: docker-compose -f docker-compose.yml up -d postgres_test redis_test

    - name: Migrate test DB
      run: make migrate_test_up

    - name: Build test
      run: docker build -t 33r01b/godmin-test -f docker/go/testing/Dockerfile .

    - name: Run test
      run: docker run 33r01b/godmin-test

    - name: Build image
      run: make image
