name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Run docker-compose
      run: docker-compose -f docker-compose.github.yml up -d

    - name: migrate
      run: make migrate_test_up

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
